const translations = {
  ru: {
    tagline: "Платформа профориентации",
    nav_about: "О проекте",
    nav_tracks: "Направления",
    nav_steps: "Как это работает",
    nav_test: "Пройти тест",
    nav_contact: "Контакты",
    hero_eyebrow: "Профессии, которые вдохновляют",
    hero_title: "Откройте путь в будущее вместе с KASBI MAN",
    hero_description:
      "Двухъязычная платформа профориентации для школьников, студентов и родителей. Осознанный выбор профессии через тесты, мастер-классы и истории успеха.",
    hero_primary: "Начать консультацию",
    hero_secondary: "Пройти профтест",
    hero_metric_1: "Профессий в каталоге",
    hero_metric_2: "Экспертов и наставников",
    hero_metric_3: "Языка: таджикский и русский",
    hero_card_title: "Быстрый старт",
    hero_card_1: "Пройдите профтест за 10 минут",
    hero_card_2: "Получите персональный маршрут",
    hero_card_3: "Запишитесь на консультацию",
    hero_card_footer: "Поддержка от карьерных консультантов",
    about_title: "О платформе",
    about_description:
      "KASBI MAN помогает подросткам и молодым специалистам ориентироваться в мире профессий, учиться принимать решения и планировать карьеру. Мы объединяем тестирование, контент, наставничество и локальный рынок труда в одном месте.",
    about_box_title: "Для кого мы работаем",
    about_box_1: "Школьники 7–11 классов",
    about_box_2: "Студенты и выпускники",
    about_box_3: "Родители и наставники",
    tracks_title: "Популярные направления",
    track_1_title: "IT и цифровые технологии",
    track_1_desc: "Программирование, анализ данных, кибербезопасность и дизайн.",
    track_2_title: "Медицина и бионауки",
    track_2_desc: "Путь врача, фармацевта, лабораторного специалиста.",
    track_3_title: "Бизнес и финансы",
    track_3_desc: "Маркетинг, предпринимательство, банковское дело.",
    track_4_title: "Образование и гуманитарные науки",
    track_4_desc: "Педагогика, психология, журналистика, перевод.",
    steps_title: "Как это работает",
    step_1_title: "Диагностика интересов",
    step_1_desc: "Тесты и опросники формируют ваш профиль интересов и сильных сторон.",
    step_2_title: "Персональная карта профессий",
    step_2_desc: "Алгоритм показывает профессии, которые подходят именно вам.",
    step_3_title: "Поддержка наставника",
    step_3_desc: "Консультации, вебинары и истории выпускников.",
    step_4_title: "План действий",
    step_4_desc: "Учебные рекомендации, список курсов и цели на ближайший год.",
    focus_title: "Фокус на рынке Таджикистана",
    focus_desc:
      "Мы учитываем локальные университеты, востребованные профессии, государственные программы и возможности стажировок, чтобы рекомендации были актуальными.",
    focus_stat_1: "Доступ к платформе",
    focus_stat_2: "Потенциальных пользователей",
    focus_stat_3: "Поддержка двух языков",
    contact_title: "Свяжитесь с нами",
    contact_desc: "Оставьте заявку, чтобы получить доступ к демо и плану внедрения.",
    contact_name: "Имя",
    contact_email: "Email",
    contact_phone: "Телефон",
    contact_message: "Сообщение",
    contact_button: "Отправить заявку",
    footer_copy: "Профориентация для будущего поколения Таджикистана.",
    footer_address: "Душанбе · Онлайн консультации",
    test_eyebrow: "Онлайн-диагностика",
    test_title: "Профориентационный тест KASBI MAN",
    test_description:
      "Ответьте на вопросы, чтобы получить персональный профиль интересов и рекомендации по профессиям, которые подходят именно вам.",
    test_meta_1: "⏱ 12 минут",
    test_meta_2: "📋 24 вопроса",
    test_meta_3: "📌 Результат сразу",
    test_step_1_title: "Шаг 1. Личные данные",
    test_step_1_desc: "Заполните имя, возраст и класс обучения.",
    test_step_2_title: "Шаг 2. Интересы и сильные стороны",
    test_step_2_desc: "Выберите утверждения, которые описывают вас.",
    test_step_3_title: "Шаг 3. Рекомендации",
    test_step_3_desc: "Получите список направлений и дальнейшие шаги.",
    test_form_title: "Начните тест",
    test_form_name_label: "Имя",
    test_form_name_placeholder: "Ваше имя",
    test_form_email_label: "Email",
    test_form_email_placeholder: "example@mail.com",
    test_form_question_1: "Что вам интереснее всего?",
    test_form_question_2: "Как вы предпочитаете работать?",
    test_option_1: "Технологии и IT",
    test_option_2: "Медицина и биология",
    test_option_3: "Бизнес и финансы",
    test_option_4: "Креатив и гуманитарные науки",
    test_option_5: "Командно и с людьми",
    test_option_6: "Самостоятельно и аналитически",
    test_option_7: "Через практику и эксперименты",
    test_form_submit: "Получить результат",
    test_support_title: "Что вы получите после теста",
    test_support_desc:
      "Мы покажем подходящие профессии, образовательные программы в Таджикистане и предложим консультацию с карьерным наставником.",
    test_summary_title: "Ваш персональный отчет",
    test_summary_1: "Профиль интересов и навыков",
    test_summary_2: "Список профессий и вузов",
    test_summary_3: "Рекомендации по следующим шагам",
  },
  tj: {
    tagline: "Платформаи касбсамтгирӣ",
    nav_about: "Дар бораи лоиҳа",
    nav_tracks: "Самтҳо",
    nav_steps: "Чӣ гуна кор мекунад",
    nav_test: "Супоридани тест",
    nav_contact: "Тамос",
    hero_eyebrow: "Касбҳое, ки илҳом мебахшанд",
    hero_title: "Роҳи ояндаро бо KASBI MAN пайдо кунед",
    hero_description:
      "Платформаи ду забона барои касбсамтгирӣ барои хонандагон, донишҷӯён ва волидайн. Интихоби бошууронаи касб тавассути тестҳо, мастер-классҳо ва ҳикояҳои муваффақият.",
    hero_primary: "Оғози машварат",
    hero_secondary: "Супоридани тест",
    hero_metric_1: "Касб дар рӯйхат",
    hero_metric_2: "Мутахассисон ва менторҳо",
    hero_metric_3: "Забонҳо: тоҷикӣ ва русӣ",
    hero_card_title: "Оғози зуд",
    hero_card_1: "Тести касбро дар 10 дақиқа гузаред",
    hero_card_2: "Роҳнамои шахсӣ гиред",
    hero_card_3: "Ба машварат сабт шавед",
    hero_card_footer: "Дастгирии мушовирони касбӣ",
    about_title: "Дар бораи платформа",
    about_description:
      "KASBI MAN ба наврасон ва ҷавонон кӯмак мекунад, ки дар ҷаҳони касбҳо роҳнамоӣ шуда, қарорҳои дуруст ва нақшаи касбиро интихоб кунанд. Мо тестҳо, контент, менторӣ ва бозори меҳнати маҳаллиро дар як ҷо ҷамъ мекунем.",
    about_box_title: "Барои кӣ хизмат мекунем",
    about_box_1: "Хонандагони синфҳои 7–11",
    about_box_2: "Донишҷӯён ва хатмкунандагон",
    about_box_3: "Волидайн ва роҳнамоён",
    tracks_title: "Самтҳои маъмул",
    track_1_title: "IT ва технологияҳои рақамӣ",
    track_1_desc: "Барномасозӣ, таҳлили маълумот, киберамният ва дизайн.",
    track_2_title: "Тиб ва бионаука",
    track_2_desc: "Роҳи табиб, дорусоз, мутахассиси лаборатория.",
    track_3_title: "Бизнес ва молия",
    track_3_desc: "Маркетинг, соҳибкорӣ, корҳои бонкӣ.",
    track_4_title: "Маориф ва илмҳои гуманитарӣ",
    track_4_desc: "Педагогика, равоншиносӣ, журналистика, тарҷума.",
    steps_title: "Чӣ гуна кор мекунад",
    step_1_title: "Ташхиси шавқ",
    step_1_desc: "Тестҳо ва пурсишҳо профили шавқу қувваҳоро нишон медиҳанд.",
    step_2_title: "Харитаи шахсии касбҳо",
    step_2_desc: "Алгоритм касбҳои мувофиқро пешниҳод мекунад.",
    step_3_title: "Дастгирии ментор",
    step_3_desc: "Машваратҳо, вебинарҳо ва ҳикояҳои хатмкунандагон.",
    step_4_title: "Нақшаи амал",
    step_4_desc: "Тавсияҳои таҳсил, рӯйхати курсҳо ва ҳадафҳо барои соли наздик.",
    focus_title: "Таваҷҷӯҳ ба бозори Тоҷикистон",
    focus_desc:
      "Мо донишгоҳҳои маҳаллӣ, касбҳои серталаб, барномаҳои давлатӣ ва имкониятҳои таҷрибаро ба назар мегирем, то тавсияҳо актуалӣ бошанд.",
    focus_stat_1: "Дастрасӣ ба платформа",
    focus_stat_2: "Истифодабарандагони эҳтимолӣ",
    focus_stat_3: "Дастгирии ду забон",
    contact_title: "Бо мо тамос гиред",
    contact_desc: "Дархост гузоред, то ба демо ва нақшаи татбиқ дастрасӣ гиред.",
    contact_name: "Ном",
    contact_email: "Email",
    contact_phone: "Телефон",
    contact_message: "Паём",
    contact_button: "Дархост фиристед",
    footer_copy: "Касбсамтгирӣ барои насли ояндаи Тоҷикистон.",
    footer_address: "Душанбе · Машваратҳои онлайн",
    test_eyebrow: "Ташхиси онлайн",
    test_title: "Тести касбсамтгирии KASBI MAN",
    test_description:
      "Ба саволҳо ҷавоб диҳед, то профили шавқ ва тавсияҳои касбҳои мувофиқро гиред.",
    test_meta_1: "⏱ 12 дақиқа",
    test_meta_2: "📋 24 савол",
    test_meta_3: "📌 Натиҷа фавран",
    test_step_1_title: "Қадам 1. Маълумоти шахсӣ",
    test_step_1_desc: "Ном, синну сол ва синфи таҳсилро ворид кунед.",
    test_step_2_title: "Қадам 2. Шавқ ва қувваҳо",
    test_step_2_desc: "Изҳоротеро интихоб кунед, ки шуморо тавсиф мекунанд.",
    test_step_3_title: "Қадам 3. Тавсияҳо",
    test_step_3_desc: "Самтҳои мувофиқ ва қадамҳои минбаъдаро гиред.",
    test_form_title: "Тестро оғоз кунед",
    test_form_name_label: "Ном",
    test_form_name_placeholder: "Номи шумо",
    test_form_email_label: "Email",
    test_form_email_placeholder: "example@mail.com",
    test_form_question_1: "Чӣ бештар ба шумо писанд аст?",
    test_form_question_2: "Шумо чӣ гуна кор карданро дӯст медоред?",
    test_option_1: "Технология ва IT",
    test_option_2: "Тиб ва биология",
    test_option_3: "Бизнес ва молия",
    test_option_4: "Эҷод ва илмҳои гуманитарӣ",
    test_option_5: "Командӣ ва бо одамон",
    test_option_6: "Мустақилона ва таҳлилӣ",
    test_option_7: "Тавассути амал ва таҷриба",
    test_form_submit: "Гирифтани натиҷа",
    test_support_title: "Пас аз тест чӣ мегиред",
    test_support_desc:
      "Мо касбҳои мувофиқ, барномаҳои таҳсилӣ дар Тоҷикистон ва машварат бо мураббиро пешниҳод мекунем.",
    test_summary_title: "Ҳисоботи шахсии шумо",
    test_summary_1: "Профили шавқ ва малакаҳо",
    test_summary_2: "Рӯйхати касбҳо ва донишгоҳҳо",
    test_summary_3: "Тавсияҳо барои қадамҳои навбатӣ",
  },
};

const applyTranslations = (lang) => {
  document.documentElement.lang = lang === "tj" ? "tg" : "ru";
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    const value = translations[lang][key];
    if (value) {
      element.textContent = value;
    }
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    const key = element.dataset.i18nPlaceholder;
    const value = translations[lang][key];
    if (value) {
      element.setAttribute("placeholder", value);
    }
  });
};

const buttons = document.querySelectorAll(".lang-button");
buttons.forEach((button) => {
  button.addEventListener("click", () => {
    buttons.forEach((btn) => btn.classList.remove("is-active"));
    button.classList.add("is-active");
    applyTranslations(button.dataset.lang);
  });
});

applyTranslations("ru");
